USE sofi_db;

-- 1. Actualizar DESARROLLO
ALTER TABLE DESARROLLO ADD COLUMN Descripcion TEXT;
ALTER TABLE DESARROLLO ADD COLUMN Estatus ENUM('Activo', 'Preventa', 'Cerrado') DEFAULT 'Activo';

-- 2. Actualizar CLIENTE
ALTER TABLE CLIENTE ADD COLUMN Email VARCHAR(150);
ALTER TABLE CLIENTE ADD COLUMN Estatus ENUM('Activo', 'Inactivo') DEFAULT 'Activo';

-- 3. Actualizar CONTRATO
ALTER TABLE CONTRATO ADD COLUMN Folio VARCHAR(20);
ALTER TABLE CONTRATO ADD COLUMN MontoTotal DECIMAL(12, 2) DEFAULT 0;
ALTER TABLE CONTRATO ADD COLUMN Enganche DECIMAL(12, 2) DEFAULT 0;
ALTER TABLE CONTRATO ADD COLUMN PlazoMeses INT DEFAULT 0;
ALTER TABLE CONTRATO ADD COLUMN TasaInteres DECIMAL(5, 2) DEFAULT 0;
ALTER TABLE CONTRATO ADD COLUMN Mensualidad DECIMAL(12, 2) DEFAULT 0;
ALTER TABLE CONTRATO ADD COLUMN PagosRealizados INT DEFAULT 0;
ALTER TABLE CONTRATO ADD COLUMN ProximoPago DATE;
ALTER TABLE CONTRATO ADD COLUMN Estatus ENUM('Activo', 'Vencido', 'Liquidado', 'Cancelado') DEFAULT 'Activo';

UPDATE CONTRATO SET MontoTotal = MontoFijo WHERE Folio IS NULL;
UPDATE CONTRATO SET Folio = CONCAT('CTR-', IdContrato) WHERE Folio IS NULL;

-- 4. Actualizar PAGO
ALTER TABLE PAGO ADD COLUMN MetodoPago ENUM('Efectivo', 'Transferencia', 'Tarjeta', 'Cheque') DEFAULT 'Efectivo';
ALTER TABLE PAGO ADD COLUMN Referencia VARCHAR(100);
ALTER TABLE PAGO ADD COLUMN Observaciones TEXT;
ALTER TABLE PAGO ADD COLUMN Estatus ENUM('Pagado', 'Pendiente', 'Atrasado', 'Cancelado') DEFAULT 'Pendiente';
