USE sofi_db;

-- 1. MANZANA -> DESARROLLO
ALTER TABLE MANZANA DROP FOREIGN KEY fk_manzana_desarrollo;
ALTER TABLE MANZANA ADD CONSTRAINT fk_manzana_desarrollo 
    FOREIGN KEY (IdDesarrollo) REFERENCES DESARROLLO(IdDesarrollo) 
    ON DELETE CASCADE ON UPDATE CASCADE;

-- 2. LOTE -> MANZANA
ALTER TABLE LOTE DROP FOREIGN KEY fk_lote_manzana;
ALTER TABLE LOTE ADD CONSTRAINT fk_lote_manzana 
    FOREIGN KEY (IdManzana) REFERENCES MANZANA(IdManzana) 
    ON DELETE CASCADE ON UPDATE CASCADE;

-- 3. COLINDANCIA -> LOTE
ALTER TABLE COLINDANCIA DROP FOREIGN KEY fk_colindancia_lote;
ALTER TABLE COLINDANCIA ADD CONSTRAINT fk_colindancia_lote 
    FOREIGN KEY (IdLote) REFERENCES LOTE(IdLote) 
    ON DELETE CASCADE ON UPDATE CASCADE;

-- 4. TESTIGO -> CLIENTE
ALTER TABLE TESTIGO DROP FOREIGN KEY fk_testigo_cliente;
ALTER TABLE TESTIGO ADD CONSTRAINT fk_testigo_cliente 
    FOREIGN KEY (IdCliente) REFERENCES CLIENTE(IdCliente) 
    ON DELETE CASCADE ON UPDATE CASCADE;
